name: union_shop
description: "A Flutter project for the University of Portsmouth union shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/hoodie_navy.png
    - assets/images/twitter_logo.png
    - assets/images/facebook_logo.png
    - assets/images/fidget_keyring.png
    - assets/images/usb_cable.png
    - assets/images/sweatshirt.png
    - assets/images/ports_notebook.png
    - assets/images/hoodie_white.png
    - assets/images/hoodie_green.png
    - assets/images/tee.png
    - assets/images/tee_navy.png
    - assets/images/p_bookmark.png
    - assets/images/p_postcard.png
    - assets/images/p_magnet.png


  